//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modal.StudentManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public long ID { get; set; }
        public Nullable<long> ClassID { get; set; }
        public Nullable<long> DepartmentID { get; set; }
        public string Age { get; set; }
        public string ParantsMobileNo { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Department Department { get; set; }
    }
}
